/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lg10.kaktus.utilities;

import lg10.kaktus.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
